// templates/front/next/components/UserBanner.tsx
import { useState, useCallback, ChangeEvent } from 'react'
import { apiClient } from '~/utils/apiClient'
import { UserInfo } from '~/server/types'

const UserBanner = () => {
  const [isLoggedIn, setIsLoggedIn] = useState(false)
  const [token, setToken] = useState('')
  const [userInfo, setUserInfo] = useState({} as UserInfo)

  const editIcon = useCallback(
    async (e: ChangeEvent<HTMLInputElement>) => {
      if (!e.target.files?.length) return

      setUserInfo(
        await apiClient.user.$post({
          headers: { token },
          data: { icon: e.target.files[0] }
        })
      )
    },
    [token]
  )

  const login = useCallback(async () => {
    const id = prompt('Enter the user id (See .env)')
    const pass = prompt('Enter the user pass (See .env)')
    if (!id || !pass) return alert('Login failed')

    let newToken = ''

    try {
      newToken = (await apiClient.token.$post({ data: { id, pass } })).token
      setToken(newToken)
    } catch (e) {
      return alert('Login failed')
    }

    setUserInfo(await apiClient.user.$get({ headers: { token: newToken } }))
    setIsLoggedIn(true)
  }, [])

  const logout = useCallback(async () => {
    await apiClient.token.delete({ headers: { token } })
    setToken('')
    setIsLoggedIn(false)
  }, [token])

  return (
    <div className="user-banner">
      {isLoggedIn ? (
        <div>
          <img src={userInfo.icon} className="user-icon" />
          <span>{userInfo.name}</span>
          <input type="file" accept="image/*" onChange={editIcon} />
          <button onClick={logout}>LOGOUT</button>
        </div>
      ) : (
        <button onClick={login}>LOGIN</button>
      )}

      <style jsx>{`
        .user-banner {
          position: fixed;
          top: 0;
          right: 0;
          padding: 20px;
        }

        .user-icon {
          width: 32px;
          height: 32px;
          background: #ddd;
          vertical-align: bottom;
        }
      `}</style>
    </div>
  )
}

export default UserBanner

// templates/front/nuxt/components/UserBanner.vue
<template>
  <div class="user-banner">
    <div v-if="isLoggedIn">
      <img :src="userInfo.icon" class="user-icon" />
      <span>{{ userInfo.name }}</span>
      <input type="file" accept="image/*" @change="editIcon" />
      <button @click="logout">LOGOUT</button>
    </div>
    <button v-else @click="login">LOGIN</button>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import { UserInfo } from '~/server/types'

export default Vue.extend({
  data() {
    return {
      isLoggedIn: false,
      userInfo: {} as UserInfo,
      token: ''
    }
  },
  methods: {
    async editIcon(e: { target: HTMLInputElement }) {
      if (!e.target?.files?.length) return

      this.userInfo = await this.$api.user.$post({
        headers: { token: this.token },
        data: { icon: e.target.files[0] }
      })
    },
    async login() {
      const id = prompt('Enter the user id (See .env)')
      const pass = prompt('Enter the user pass (See .env)')
      if (!id || !pass) return alert('Login failed')

      try {
        this.token = (await this.$api.token.$post({ data: { id, pass } })).token
      } catch (e) {
        return alert('Login failed')
      }

      this.userInfo = await this.$api.user.$get({
        headers: { token: this.token }
      })
      this.isLoggedIn = true
    },
    async logout() {
      await this.$api.token.delete({
        headers: { token: this.token }
      })
      this.token = ''
      this.isLoggedIn = false
    }
  }
})
</script>

<style scoped>
.user-banner {
  position: fixed;
  top: 0;
  right: 0;
  padding: 20px;
}

.user-icon {
  width: 32px;
  height: 32px;
  background: #ddd;
  vertical-align: bottom;
}
</style>
