// server/templates/@client=nuxt/components/UserBanner.vue
<template>
  <div class="user-banner">
    <div class="navs">
      <NuxtLink :to="$pagesPath.$url()" class="nav">Home</NuxtLink>
      <NuxtLink :to="$pagesPath.article.$url()" class="nav">Article</NuxtLink>
      <form @submit="submit">
        <input :value="search" @change="changeSearch" />
        <button type="submit">search</button>
      </form>
    </div>
    <div>
      <template v-if="isLoggedIn">
        <img :src="userInfo.icon" class="user-icon" />
        <span>{{ userInfo.name }}</span>
        <input type="file" accept="image/*" @change="editIcon" />
        <button @click="logout">LOGOUT</button>
      </template>
      <button v-else @click="login">LOGIN</button>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import type { UserInfo } from '$/types'

export default Vue.extend({
  data() {
    return {
      isLoggedIn: false,
      userInfo: {} as UserInfo,
      token: '',
      search:
        typeof this.$route.query.search === 'string'
          ? this.$route.query.search
          : undefined
    }
  },
  methods: {
    async editIcon(e: { target: HTMLInputElement }) {
      if (!e.target?.files?.length) return

      this.userInfo = await this.$api.user.$post({
        headers: { authorization: this.token },
        body: { icon: e.target.files[0] }
      })
    },
    async login() {
      const id = prompt('Enter the user id (See server/.env)')
      const pass = prompt('Enter the user pass (See server/.env)')
      if (!id || !pass) return alert('Login failed')

      try {
        this.token = `Bearer ${
          (await this.$api.token.$post({ body: { id, pass } })).token
        }`
      } catch (e) {
        return alert('Login failed')
      }

      this.userInfo = await this.$api.user.$get({
        headers: { authorization: this.token }
      })
      this.isLoggedIn = true
    },

    logout() {
      this.token = ''
      this.isLoggedIn = false
    },
    changeSearch(event: Event) {
      if (event.target instanceof HTMLInputElement) {
        this.search = event.target.value
      }
    },
    submit(event: Event) {
      event.preventDefault()
      this.$router.push(
        this.$pagesPath.article.$url({ query: { search: this.search } })
      )
    }
  }
})
</script>

<style scoped>
.user-icon {
  width: 32px;
  height: 32px;
  background: #ddd;
  vertical-align: bottom;
}

.user-banner {
  display: flex;
  justify-content: space-between;
  padding: 20px;
  width: 100%;
  position: fixed;
  align-items: center;
}
.navs {
  display: flex;
  justify-content: center;
  align-items: center;
}

.nav {
  padding: 8px;
  border-bottom: 3px solid transparent;
  transition: all 0.2s;
  text-decoration: none;
  color: black;
}

.nav:hover {
  border-bottom: 3px solid #000;
}
</style>

// server/templates/@client=next/src/components/UserBanner.tsx
import { useState, useCallback } from 'react'
import styles from '~/styles/UserBanner.module.css'
import { apiClient } from '~/utils/apiClient'
import type { UserInfo } from '$/types'
import type { ChangeEvent } from 'react'
import Link from 'next/link'
import { pagesPath } from '~/utils/$path'
import { useRouter } from 'next/router'

const UserBanner = () => {
  const router = useRouter()
  const [search, setSearch] = useState('')
  const [isLoggedIn, setIsLoggedIn] = useState(false)
  const [token, setToken] = useState('')
  const [userInfo, setUserInfo] = useState({} as UserInfo)

  const editIcon = useCallback(
    async (e: ChangeEvent<HTMLInputElement>) => {
      if (!e.target.files?.length) return

      setUserInfo(
        await apiClient.user.$post({
          headers: { authorization: token },
          body: { icon: e.target.files[0] }
        })
      )
    },
    [token]
  )

  const login = useCallback(async () => {
    const id = prompt('Enter the user id (See server/.env)')
    const pass = prompt('Enter the user pass (See server/.env)')
    if (!id || !pass) return alert('Login failed')

    let newToken = ''

    try {
      newToken = `Bearer ${
        (await apiClient.token.$post({ body: { id, pass } })).token
      }`
      setToken(newToken)
    } catch (e) {
      return alert('Login failed')
    }

    setUserInfo(
      await apiClient.user.$get({ headers: { authorization: newToken } })
    )
    setIsLoggedIn(true)
  }, [])

  const logout = useCallback(() => {
    setToken('')
    setIsLoggedIn(false)
  }, [])

  return (
    <div>
      <div className={styles.userBanner}>
        <div>
          <Link href={pagesPath.$url()}>
            <a className={styles.nav}>Home</a>
          </Link>
          <Link href={pagesPath.article.$url()}>
            <a className={styles.nav}>Article</a>
          </Link>
        </div>
        <form
          onSubmit={(e) => {
            e.preventDefault()
            router.push(
              pagesPath.article.$url({
                query: {
                  search
                }
              })
            )
          }}
        >
          <input
            type="text"
            name="query"
            onInput={(e) =>
              e.target instanceof HTMLInputElement && setSearch(e.target.value)
            }
          />
          <button type="submit">search</button>
        </form>
        <div className={styles.spacing} />
        <div>
          {isLoggedIn ? (
            <>
              <img src={userInfo.icon} className={styles.userIcon} />
              <span>{userInfo.name}</span>
              <input type="file" accept="image/*" onChange={editIcon} />
              <button onClick={logout}>LOGOUT</button>
            </>
          ) : (
            <button onClick={login}>LOGIN</button>
          )}
        </div>
      </div>
      <div className={styles.padding} />
    </div>
  )
}

export default UserBanner
