// server/templates/@client=nuxt/pages/index.vue
<template>
  <div>
    <user-banner />
    <div class="container">
      <div>
        <logo />
        <h1 class="title">frourio-todo-app</h1>
        <div v-if="!$fetchState.pending">
          <form @submit.prevent="createTask">
            <input v-model="newLabel" type="text" />
            <input type="submit" value="ADD" />
          </form>
          <ul class="tasks">
            <li v-for="task in tasks" :key="task.id">
              <label>
                <input
                  type="checkbox"
                  :checked="task.done"
                  @change="toggleDone(task)"
                />
                <span>{{ task.label }}</span>
              </label>
              <input
                type="button"
                value="DELETE"
                style="float: right"
                @click="deleteTask(task)"
              />
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import type { Task } from '<%= orm === "prisma" ? "$prisma/client" : "$/types" %>'
import UserBanner from '~/components/UserBanner.vue'
import Logo from '~/components/Logo.vue'

export default Vue.extend({
  components: {
    UserBanner,
    Logo
  },
  data() {
    return {
      tasks: [] as Task[],
      newLabel: ''
    }
  },
  async fetch() {
    await this.fetchTasks()
  },
  methods: {
    async fetchTasks() {
      this.tasks = await this.$api.tasks.$get()
    },
    async createTask() {
      if (!this.newLabel) return

      await this.$api.tasks.post({ body: { label: this.newLabel } })
      this.newLabel = ''
      await this.fetchTasks()
    },
    async toggleDone(task: Task) {
      await this.$api.tasks
        ._taskId(task.id)
        .patch({ body: { done: !task.done } })
      await this.fetchTasks()
    },
    async deleteTask(task: Task) {
      await this.$api.tasks._taskId(task.id).delete()
      await this.fetchTasks()
    }
  }
})
</script>

<style scoped>
.container {
  margin: 0 auto;
  align-items: center;
  display: flex;
  justify-content: center;
  text-align: center;
  min-height: 100vh;
}

.title {
  font-family: 'Quicksand', 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
    'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  display: block;
  font-weight: 300;
  font-size: 100px;
  color: #35495e;
  letter-spacing: 1px;
}

.tasks {
  width: 300px;
  padding: 0;
  margin: 20px auto 0;
  list-style-type: none;
  text-align: left;
}

.tasks > li {
  margin-top: 10px;
  border-bottom: 1px solid #eee;
}
</style>

// server/templates/@client=next/src/pages/index.tsx
import Head from 'next/head'
import { useCallback, <% if (reactHooks === 'none') { %>useEffect, <% } %>useState } from 'react'<% if (reactHooks === 'swr') { %>
import useAspidaSWR from '@aspida/swr'<% } else if (reactHooks === 'query') { %>
import { useQueryClient } from 'react-query'
import { useAspidaQuery } from '@aspida/react-query'<% } %>
import styles from '~/styles/Home.module.css'
import { apiClient } from '~/utils/apiClient'
import type { Task } from '<%= orm === "prisma" ? "$prisma/client" : "$/types" %>'
import type { FormEvent, ChangeEvent } from 'react'
import Layout from '~/components/Layout'
import type { NextPage } from 'next'

const Home = () => {
  <% if (reactHooks === 'swr') { %>const { data: tasks, error, mutate } = useAspidaSWR(apiClient.tasks)<% } else if (reactHooks === 'query') { %>const queryClient = useQueryClient()
  const { data: tasks, error } = useAspidaQuery(apiClient.tasks)<% } else { %>const [tasks, setTasks] = useState<Task[] | undefined>(undefined)<% } %>
  const [label, setLabel] = useState('')
  const inputLabel = useCallback(
    (e: ChangeEvent<HTMLInputElement>) => setLabel(e.target.value),
    []
  )<% if (reactHooks === 'query') { %>

  const invalidateTasks = useCallback(
    () => queryClient.invalidateQueries(apiClient.tasks.$path()),
    [queryClient]
  )<% } else if (reactHooks === 'none') { %>

  const fetchTasks = useCallback(async () => {
    setTasks(await apiClient.tasks.$get())
  }, [])<% } %>

  const createTask = useCallback(
    async (e: FormEvent) => {
      e.preventDefault()
      if (!label) return

      await apiClient.tasks.post({ body: { label } })
      setLabel('')
      <% if (reactHooks === 'swr') { %>mutate<% } else if (reactHooks === 'query') { %>invalidateTasks<% } else { %>await fetchTasks<% } %>()
    },
    [label]
  )

  const toggleDone = useCallback(async (task: Task) => {
    await apiClient.tasks._taskId(task.id).patch({ body: { done: !task.done } })
    <% if (reactHooks === 'swr') { %>mutate<% } else if (reactHooks === 'query') { %>invalidateTasks<% } else { %>await fetchTasks<% } %>()
  }, [])

  const deleteTask = useCallback(async (task: Task) => {
    await apiClient.tasks._taskId(task.id).delete()
    <% if (reactHooks === 'swr') { %>mutate<% } else if (reactHooks === 'query') { %>invalidateTasks<% } else { %>await fetchTasks<% } %>()
  }, [])

  <% if (reactHooks === 'none') { %>useEffect(() => {
    fetchTasks()
  }, [])
<%  } else { %>if (error) return <div>failed to load</div><% } %>
  if (!tasks) return <div>loading...</div>

  return (
    <Layout>
      <Head>
        <title>frourio-todo-app</title>
      </Head>

      <h1 className={styles.title}>
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1>

      <p className={styles.description}>frourio-todo-app</p>

      <div>
        <form style={{ textAlign: 'center' }} onSubmit={createTask}>
          <input value={label} type="text" onChange={inputLabel} />
          <input type="submit" value="ADD" />
        </form>
        <ul className={styles.tasks}>
          {tasks.map((task) => (
            <li key={task.id}>
              <label>
                <input
                  type="checkbox"
                  checked={task.done}
                  onChange={() => toggleDone(task)}
                />
                <span>{task.label}</span>
              </label>
              <input
                type="button"
                value="DELETE"
                style={{ float: 'right' }}
                onClick={() => deleteTask(task)}
              />
            </li>
          ))}
        </ul>
      </div>
    </Layout>
  )
}

export default Home
