// server/templates/@client=nuxt/pages/index.vue
<template>
  <div>
    <user-banner />
    <div class="container">
      <div>
        <logo />
        <h1 class="title">frourio-todo-app</h1>
        <div v-if="!$fetchState.pending">
          <form @submit.prevent="createTask">
            <input v-model="newLabel" type="text" />
            <input type="submit" value="ADD" />
          </form>
          <ul class="tasks">
            <li v-for="task in tasks" :key="task.id">
              <label>
                <input
                  type="checkbox"
                  :checked="task.done"
                  @change="toggleDone(task)"
                />
                <span>{{ task.label }}</span>
              </label>
              <input
                type="button"
                value="DELETE"
                style="float: right"
                @click="deleteTask(task)"
              />
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import type { Task } from '<%= orm === "prisma" ? "$prisma/client" : "$/types" %>'
import UserBanner from '~/components/UserBanner.vue'
import Logo from '~/components/Logo.vue'

export default Vue.extend({
  components: {
    UserBanner,
    Logo
  },
  data() {
    return {
      tasks: [] as Task[],
      newLabel: ''
    }
  },
  async fetch() {
    await this.fetchTasks()
  },
  methods: {
    async fetchTasks() {
      this.tasks = await this.$api.tasks.$get()
    },
    async createTask() {
      if (!this.newLabel) return

      await this.$api.tasks.post({ body: { label: this.newLabel } })
      this.newLabel = ''
      await this.fetchTasks()
    },
    async toggleDone(task: Task) {
      await this.$api.tasks
        ._taskId(task.id)
        .patch({ body: { done: !task.done } })
      await this.fetchTasks()
    },
    async deleteTask(task: Task) {
      await this.$api.tasks._taskId(task.id).delete()
      await this.fetchTasks()
    }
  }
})
</script>

<style scoped>
.container {
  margin: 0 auto;
  align-items: center;
  display: flex;
  justify-content: center;
  text-align: center;
  min-height: 100vh;
}

.title {
  font-family: 'Quicksand', 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
    'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  display: block;
  font-weight: 300;
  font-size: 100px;
  color: #35495e;
  letter-spacing: 1px;
}

.tasks {
  width: 300px;
  padding: 0;
  margin: 20px auto 0;
  list-style-type: none;
  text-align: left;
}

.tasks > li {
  margin-top: 10px;
  border-bottom: 1px solid #eee;
}
</style>

// templates/front/next/pages/index.tsx
import Head from 'next/head'
import { useCallback, useState, FormEvent, ChangeEvent } from 'react'
import { apiClient } from '~/utils/apiClient'
import { Task } from '~/server/types'
import UserBanner from '~/components/UserBanner'

type Props = {
  tasks: Task[]
}

const Home = (props: Props) => {
  const [label, setLabel] = useState('')
  const [tasks, setTasks] = useState(props.tasks)

  const inputLavel = useCallback(
    (e: ChangeEvent<HTMLInputElement>) => setLabel(e.target.value),
    []
  )

  const createTask = useCallback(
    async (e: FormEvent) => {
      e.preventDefault()
      if (!label) return

      await apiClient.tasks.post({ data: { label } })
      setLabel('')
      setTasks(await apiClient.tasks.$get())
    },
    [label]
  )

  const toggleDone = useCallback(async (task: Task) => {
    await apiClient.tasks._taskId(task.id).patch({ data: { done: !task.done } })
    setTasks(await apiClient.tasks.$get())
  }, [])

  const removeTask = useCallback(async (task: Task) => {
    await apiClient.tasks._taskId(task.id).delete()
    setTasks(await apiClient.tasks.$get())
  }, [])

  return (
    <div className="container">
      <Head>
        <title>frourio-todo-app</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <UserBanner />

        <h1 className="title">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className="description">frourio-todo-app</p>

        <div>
          <form style={{ textAlign: 'center' }} onSubmit={createTask}>
            <input value={label} type="text" onChange={inputLavel} />
            <input type="submit" value="ADD" />
          </form>
          <ul className="tasks">
            {tasks.map((task) => (
              <li key={task.id}>
                <label>
                  <input
                    type="checkbox"
                    checked={task.done}
                    onChange={() => toggleDone(task)}
                  />
                  <span>{task.label}</span>
                </label>
                <input
                  type="button"
                  value="DELETE"
                  style={{ float: 'right' }}
                  onClick={() => removeTask(task)}
                />
              </li>
            ))}
          </ul>
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <img src="/vercel.svg" alt="Vercel Logo" className="logo" />
        </a>
      </footer>

      <style jsx>{`
        .container {
          min-height: 100vh;
          padding: 0 0.5rem;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
        }

        main {
          padding: 5rem 0;
          flex: 1;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
        }

        footer {
          width: 100%;
          height: 100px;
          border-top: 1px solid #eaeaea;
          display: flex;
          justify-content: center;
          align-items: center;
        }

        footer img {
          margin-left: 0.5rem;
        }

        footer a {
          display: flex;
          justify-content: center;
          align-items: center;
        }

        a {
          color: inherit;
          text-decoration: none;
        }

        .title a {
          color: #0070f3;
          text-decoration: none;
        }

        .title a:hover,
        .title a:focus,
        .title a:active {
          text-decoration: underline;
        }

        .title {
          margin: 0;
          line-height: 1.15;
          font-size: 4rem;
        }

        .title,
        .description {
          text-align: center;
        }

        .description {
          line-height: 1.5;
          font-size: 1.5rem;
        }

        .logo {
          height: 1em;
        }

        .tasks {
          width: 300px;
          padding: 0;
          margin: 20px auto 0;
          list-style-type: none;
          text-align: left;
        }

        .tasks > li {
          margin-top: 10px;
          border-bottom: 1px solid #eee;
        }
      `}</style>

      <style jsx global>{`
        html,
        body {
          padding: 0;
          margin: 0;
          font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto,
            Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue,
            sans-serif;
        }

        * {
          box-sizing: border-box;
        }
      `}</style>
    </div>
  )
}

Home.getInitialProps = async () => ({
  tasks: await apiClient.tasks.$get()
})

export default Home
